@SimplePostgresConnector_HostAddress = http://localhost:5277

GET {{SimplePostgresConnector_HostAddress}}/get-employees/
Accept: application/json

###

GET {{SimplePostgresConnector_HostAddress}}/get-employees/{title}
Accept: application/json

###

POST {{SimplePostgresConnector_HostAddress}}/add-employee/
Accept: application/json

###

POST {{SimplePostgresConnector_HostAddress}}/add-company/
Accept: application/json

###
